services:
  app:
    container_name: rustApp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/target
      - ~/.ssh:/root/.ssh:ro # ホストの~/.sshディレクトリをコンテナの/root/.sshに読み取り専用でマウント
      - ~/.gitconfig:/root/.gitconfig:ro # ホストの~/.gitconfigをコンテナに読み取り専用でマウント
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
